### ISSUE TITLE
"Out of date" notification appears for up to date mod.

### ISSUE THREAD

**Issue by renatamer** [VisualError/CompatibilityChecker#6]
[EmployeeAssignments 1.1.0](https://thunderstore.io/c/lethal-company/p/amnsoft/EmployeeAssignments/) results in a notification, even when using latest version of the mod.

![imagen](https://github.com/VisualError/CompatibilityChecker/assets/49537750/99f1219f-1b00-4279-b66f-6e92506940c9)

**Comment by VisualError** [comment]
This notification wasn't made by compatibility checker.
